version: 1
services:
  - type: web
    name: my-service
    env: node
    buildCommand: "npm install && npm run build"
    startCommand: "node dist/index.js"
    envVars:
      - key: NODE_ENV
        value: production
